### ISSUE TITLE
Broken Repo

### ISSUE THREAD

**Issue by w-thomas89** [Henchman117/Dealership#6]
It looks like Roman didn't perform an upstream fetch before commiting her repo and doing a Pull Request. This caused a backlog of the commits performed from my fork and broke the link. Lets look into getting this fixed ASAP. This repo should show about 18 commits. It shows ONE.

**Comment by Henchman117** [comment]
I believe I'm the one who broke the repo. I was trying to push the customer entity but it wouldn't let me. I read online about a -f command when pushing and for some reason it's deleted everything. Theres ways to fix it so I'll try them. I have a log of all our commits.

**Comment by Henchman117** [comment]
I created a recovery branch of the previous commits.
